import type { Metadata, Viewport } from 'next';
import { Outfit, JetBrains_Mono } from 'next/font/google';
import '@astryxdesign/core/reset.css';
import '@astryxdesign/core/astryx.css';
// Generated by `npx astryx theme build packages/theme/src/smartkasiTheme.ts`
// (run it again whenever packages/theme/src/tokens.json changes).
import '../../../../packages/theme/src/smartkasi.css';
import './globals.css';
import Providers from './providers';

const outfit = Outfit({ variable: '--font-outfit', subsets: ['latin'] });
const jetbrains = JetBrains_Mono({ variable: '--font-jetbrains', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SmartKasi — Township Commerce Admin',
  description:
    'Offline POS, barcode inventory, price comparison, license verification, map & flyers for spaza shops',
  manifest: '/manifest.json',
  appleWebApp: { capable: true, title: 'SmartKasi', statusBarStyle: 'default' },
};

export const viewport: Viewport = {
  themeColor: '#0F766E',
  width: 'device-width',
  initialScale: 1,
};

// Pins the theme before first paint. Default is LIGHT for everyone — dark
// only applies when the user explicitly chose it (providers.tsx toggle).
// Also sets color-scheme + canvas colour inline so the page is correct even
// before any stylesheet lands (dev injects CSS via JS after first paint).
// Kept in sync with providers.tsx (THEME_MODE_KEY) and tokens.json (bodyDark).
const THEME_MODE_INIT = `try{var m=localStorage.getItem('smartkasi_theme_mode');var d=document.documentElement;if(m==='dark'){d.setAttribute('data-theme','dark');d.style.colorScheme='dark';d.style.backgroundColor='#0F172A';}else{d.setAttribute('data-theme','light');d.style.colorScheme='light';}}catch(e){}`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`h-full antialiased ${outfit.variable} ${jetbrains.variable}`}
    >
      <body style={{ fontFamily: 'var(--_theme-body-font, Outfit), sans-serif' }}>
        <script dangerouslySetInnerHTML={{ __html: THEME_MODE_INIT }} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
