/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: packages\theme\src\smartkasiTheme.ts
 * Command: astryx theme build packages\theme\src\smartkasiTheme.ts
 * CLI: @astryxdesign/cli@0.4.6
 * Core: @astryxdesign/core@0.4.6
 */

/**
 * smartkasi theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { smartkasiTheme } from './smartkasi';
 *   import './smartkasi.css';
 */
export const smartkasiTheme = {
  name: 'smartkasi',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.3125rem",
    "--font-size-3xs": "0.375rem",
    "--font-size-2xs": "0.4375rem",
    "--font-size-xs": "0.5625rem",
    "--font-size-sm": "0.6875rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.6875rem",
    "--font-size-3xl": "2.125rem",
    "--font-size-4xl": "2.6875rem",
    "--font-size-5xl": "3.3125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "600",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "700",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.4545",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.7778",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4545",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.283",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2093",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2941",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "Outfit, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "Outfit, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "\"JetBrains Mono\", \"SF Mono\", Monaco, Consolas, monospace",
    "--color-syntax-keyword": "light-dark(#0F766E, #5EEAD4)",
    "--color-syntax-string": "light-dark(#065F46, #A7F3D0)",
    "--color-syntax-comment": "light-dark(#57534E, #A8A29E)",
    "--color-syntax-number": "light-dark(#92400E, #FDE68A)",
    "--color-syntax-function": "light-dark(#0F766E, #99F6E4)",
    "--color-syntax-type": "light-dark(#115E59, #5EEAD4)",
    "--color-syntax-variable": "light-dark(#57534E, #A8A29E)",
    "--color-syntax-operator": "light-dark(#57534E, #A8A29E)",
    "--color-syntax-constant": "light-dark(#92400E, #FDE68A)",
    "--color-syntax-tag": "light-dark(#115E59, #5EEAD4)",
    "--color-syntax-attribute": "light-dark(#57534E, #A8A29E)",
    "--color-syntax-property": "light-dark(#0F766E, #5EEAD4)",
    "--color-syntax-punctuation": "light-dark(#57534E, #A8A29E)",
    "--color-syntax-background": "light-dark(#FFFFFF, #0F172A)",
    "--color-accent": "light-dark(#0F766E, #14B8A6)",
    "--color-accent-muted": "light-dark(#0F766E14, #14B8A640)",
    "--color-text-accent": "light-dark(#0F766E, #14B8A6)",
    "--color-icon-accent": "light-dark(#0F766E, #14B8A6)",
    "--color-on-accent": "#ffffff",
    "--color-neutral": "light-dark(#0F172A0F, #F1F5F91A)",
    "--color-background-body": "light-dark(#FFFFFF, #0F172A)",
    "--color-background-surface": "light-dark(#FFFFFF, #1E293B)",
    "--color-background-card": "light-dark(#FFFFFF, #1E293B)",
    "--color-background-popover": "light-dark(#FFFFFF, #1E293B)",
    "--color-background-muted": "light-dark(#F1F5F9, #1E293B)",
    "--color-background-inverted": "light-dark(#0F172A, #FFFFFF)",
    "--color-overlay": "light-dark(#0F172A80, #00000099)",
    "--color-overlay-hover": "light-dark(#0F172A0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#0F172A1A, #FFFFFF1A)",
    "--color-text-primary": "light-dark(#0F172A, #F1F5F9)",
    "--color-text-secondary": "light-dark(#64748B, #94A3B8)",
    "--color-text-disabled": "light-dark(#CBD5E1, #475569)",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#0F172A",
    "--color-icon-primary": "light-dark(#0F172A, #F1F5F9)",
    "--color-icon-secondary": "light-dark(#64748B, #94A3B8)",
    "--color-icon-disabled": "light-dark(#CBD5E1, #475569)",
    "--color-success": "#0F766E",
    "--color-success-muted": "#0F766E14",
    "--color-warning": "#F59E0B",
    "--color-warning-muted": "#F59E0B14",
    "--color-error": "#EF4444",
    "--color-error-muted": "#EF444414",
    "--color-on-success": "#ffffff",
    "--color-on-error": "#ffffff",
    "--color-on-warning": "#1C1917",
    "--color-border": "light-dark(#E2E8F0, #334155)",
    "--color-border-emphasized": "light-dark(#CBD5E1, #475569)",
    "--color-skeleton": "light-dark(#E2E8F0, #334155)",
    "--color-shadow": "light-dark(#0F172A0A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-teal": "light-dark(#CCFBF1, #134E4A)",
    "--color-border-teal": "light-dark(#5EEAD4, #0F766E)",
    "--color-icon-teal": "light-dark(#0F766E, #14B8A6)",
    "--color-text-teal": "light-dark(#0F766E, #14B8A6)",
    "--color-background-green": "light-dark(#CCFBF1, #134E4A)",
    "--color-border-green": "light-dark(#5EEAD4, #0F766E)",
    "--color-icon-green": "light-dark(#0F766E, #14B8A6)",
    "--color-text-green": "light-dark(#0F766E, #14B8A6)",
    "--radius-none": "0px",
    "--radius-element": "0.75rem",
    "--radius-container": "1rem",
    "--radius-page": "1.5rem",
    "--radius-full": "9999px",
    "--radius-inner": "0.375rem",
    "--shadow-low": "0 1px 2px #0F172A0D, 0 4px 8px #0F172A0A",
    "--shadow-med": "0 4px 12px #0F172A0A, 0 8px 24px #0F172A0F",
    "--shadow-high": "0 8px 24px #0F172A0F, 0 16px 32px #0F172A14",
    "--size-element-sm": "32px",
    "--size-element-md": "40px",
    "--size-element-lg": "48px"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "paddingBlock": "var(--spacing-3)",
        "paddingInline": "var(--spacing-4)"
      },
      "variant:secondary": {
        "backgroundColor": "transparent",
        "borderWidth": "1.5px",
        "borderStyle": "solid",
        "borderColor": "#0F766E",
        "color": "#0F766E",
        ":hover": {
          "backgroundColor": "#0F766E14"
        }
      },
      "variant:ghost": {
        "color": "#0F766E"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-container)",
        "padding": "var(--spacing-4)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-4)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
