/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: packages\theme\src\smartkasiTheme.ts
 * Command: astryx theme build packages\theme\src\smartkasiTheme.ts
 * CLI: @astryxdesign/cli@0.4.6
 * Core: @astryxdesign/core@0.4.6
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const smartkasiTheme: DefinedTheme;
